CREATE DATABASE PET_SALON;

USE PET_SALON;

DROP TABLE IF EXISTS CLIENT;
CREATE TABLE CLIENT(
	ClientID	INT NOT NULL,
    Fname		VARCHAR(255) NOT NULL,
    MInit		VARCHAR(1) NOT NULL,
    Lname		VARCHAR(255) NOT NULL,
    Phone_number	VARCHAR(10) NOT NULL UNIQUE,
    Email		VARCHAR(255) NOT NULL UNIQUE,
    Address		VARCHAR(255),
    Birthday	DATE,
    CONSTRAINT pk_client PRIMARY KEY (ClientID)
);

DROP TABLE IF EXISTS PET;
CREATE TABLE PET(
	OwnerID		INT NOT NULL,
    Name		VARCHAR(255) NOT NULL,
    Breed		VARCHAR(255) NOT NULL,
    Species		VARCHAR(255),
    CONSTRAINT pk_pet PRIMARY KEY (OwnerID, Name),
    CONSTRAINT fk_pet_client FOREIGN KEY (OwnerID) references CLIENT(ClientID) 
);

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE(
    EmployeeID  INT NOT NULL,
    SSN         VARCHAR(255) NOT NULL UNIQUE,
    Name        VARCHAR(255) NOT NULL,
    Phone_number    VARCHAR(10) NOT NULL UNIQUE,
    Email       VARCHAR(255) NOT NULL UNIQUE,
    Hourly_wage DECIMAL(4,2),
    Salary		DECIMAL(7,2),
    CONSTRAINT pk_employee PRIMARY KEY (EmployeeID)
);

