CREATE DATABASE PET_SALON;

USE PET_SALON;

CREATE TABLE CLIENT(
	ClientID	INT NOT NULL,
    Fname		VARCHAR(255) NOT NULL,
    MInit		VARCHAR(1) NOT NULL,
    Lname		VARCHAR(255) NOT NULL,
    Phone_number	VARCHAR(10) NOT NULL UNIQUE,
    Email		VARCHAR(255) NOT NULL UNIQUE,
    Address		VARCHAR(255),
    Birthday	DATE,
    CONSTRAINT pk_client PRIMARY KEY (ClientID)
);