CREATE DATABASE PET_SALON;

USE PET_SALON;

DROP TABLE IF EXISTS CLIENT;
CREATE TABLE CLIENT(
	ClientID	INT NOT NULL,
    Fname		VARCHAR(255) NOT NULL,
    MInit		VARCHAR(1) NOT NULL,
    Lname		VARCHAR(255) NOT NULL,
    Phone_number	VARCHAR(10) NOT NULL UNIQUE,
    Email		VARCHAR(255) NOT NULL UNIQUE,
    Address		VARCHAR(255),
    Birthday	DATE,
    CONSTRAINT pk_client PRIMARY KEY (ClientID)
);

DROP TABLE IF EXISTS STORE_PRODUCTS;
CREATE TABLE STORE_PRODUCTS(
	ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    Brand VARCHAR(255) NOT NULL,
    Price FLOAT(2),
    CONSTRAINT pk_storeproducts PRIMARY KEY (ProductID, quantity)
    );
    
DROP TABLE IF EXISTS SPECIES;
CREATE TABLE SPECIES(
	Name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_species PRIMARY KEY (Name)
    );
    
DROP TABLE IF EXISTS PRODUCT_SPECIES;
CREATE TABLE PRODUCT_SPECIES(
	StoreProduct INT NOT NULL,
    Species VARCHAR(255) NOT NULL,
    CONSTRAINT fk_productspecies_storeproducts FOREIGN KEY (StoreProduct) references STORE_PRODUCTS(ProductID), 
	CONSTRAINT fk_productspecies_species FOREIGN KEY (Species) references SPECIES (Name) 
    );

DROP TABLE IF EXISTS PET;
CREATE TABLE PET(
	OwnerID		INT NOT NULL,
    Name		VARCHAR(255) NOT NULL,
    Breed		VARCHAR(255) NOT NULL,
    Species		VARCHAR(255),
    CONSTRAINT pk_pet PRIMARY KEY (OwnerID, Name),
    CONSTRAINT fk_pet_client FOREIGN KEY (OwnerID) references CLIENT(ClientID) 
);